# Extracting RGB values of 3D Array

RGB images are represented in 3D NumPy arrays where each element of the array represents a pixel in the image. The dimensions of the 3D array are height, width, and color channels (Red, Green and Blue).

In a typical RGB image, there are 3 color channels for every pixel - the red channel, green channel, and blue channel. Each channel value can range from 0 to 255, represented by an 8-bit number. The combination of these three channels makes up the pixel's color.

To extract the RGB values of a single pixel in a 3D NumPy array representing an RGB image, you can use indexing. For example, take the following array representing a 2x2 RGB image:

In [1]:
import numpy as np

In [2]:
rgb_arr = np.array([[[255, 0, 0], [0, 255, 0]],
                    [[0, 0, 255], [255, 255, 0]]])

In [3]:
rgb_arr

array([[[255,   0,   0],
        [  0, 255,   0]],

       [[  0,   0, 255],
        [255, 255,   0]]])

To extract the RGB values of the pixel at position (0, 1) in the array, you can use indexing as follows:

In [4]:
r_value = rgb_arr[0, 1, 0]
g_value = rgb_arr[0, 1, 1]
b_value = rgb_arr[0, 1, 2]
print(r_value, g_value, b_value)

0 255 0


To extract the RGB values of the pixel at position (1, 1) in the array, you can use indexing as follows:

In [5]:
r = rgb_arr[1,1,0]
g = rgb_arr[1,1,1]
b = rgb_arr[1,1,2]
print(r,g,b)

255 255 0


In [7]:
# Values at position (1,1)
rgb_arr[1,1,:]

array([255, 255,   0])

In [8]:
# Values at position (0,1)
rgb_arr[0,1,:]

array([  0, 255,   0])

### Applying functions to 3d arrays

In [9]:
image = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
    [[255, 255, 255], [0, 0, 0], [128, 128, 128]]
])

In [14]:
image

array([[[255,   0,   0],
        [  0, 255,   0],
        [  0,   0, 255]],

       [[255, 255, 255],
        [  0,   0,   0],
        [128, 128, 128]]])

In [20]:
image.shape

(2, 3, 3)

In [24]:
image[0,0,:]
# or
# r = image[0,0,0]
# g = image[0,0,1]
# b = image[0,0,2]

array([255,   0,   0])

In [25]:
image[0,1,:]

array([  0, 255,   0])

In [38]:
def threshold(rgb):
    print(rgb)
    r, g, b = rgb
    return 0 if r < 128 and g < 128 and b < 128 else 1

In [39]:
binary_image = np.apply_along_axis(threshold, axis=2, arr=image)

[255   0   0]
[  0 255   0]
[  0   0 255]
[255 255 255]
[0 0 0]
[128 128 128]


In [41]:
binary_image.shape

(2, 3)

In [42]:
binary_image

array([[1, 1, 1],
       [1, 0, 1]])

In [55]:
def process_color(rgb):
    print(rgb)
    r, g, b = (rgb + 100)%256
    print(r, g, b)
    return r, g, b

In [56]:
output_img = np.apply_along_axis(func1d=process_color,axis=2,arr=image)

[255   0   0]
99 100 100
[  0 255   0]
100 99 100
[  0   0 255]
100 100 99
[255 255 255]
99 99 99
[0 0 0]
100 100 100
[128 128 128]
228 228 228


In [50]:
output_img

array([[[ 99, 100, 100],
        [100,  99, 100],
        [100, 100,  99]],

       [[ 99,  99,  99],
        [100, 100, 100],
        [228, 228, 228]]])